//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./OutRecom_types');
//HELPER FUNCTIONS AND STRUCTURES

var OutRecommendService_get_args = function(args) {
  this.userid = null;
  this.num = null;
  this.mediaid = null;
  if (args) {
    if (args.userid !== undefined && args.userid !== null) {
      this.userid = args.userid;
    }
    if (args.num !== undefined && args.num !== null) {
      this.num = args.num;
    }
    if (args.mediaid !== undefined && args.mediaid !== null) {
      this.mediaid = args.mediaid;
    }
  }
};
OutRecommendService_get_args.prototype = {};
OutRecommendService_get_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.userid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.num = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.mediaid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_get_args.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_get_args');
  if (this.userid !== null && this.userid !== undefined) {
    output.writeFieldBegin('userid', Thrift.Type.I32, 1);
    output.writeI32(this.userid);
    output.writeFieldEnd();
  }
  if (this.num !== null && this.num !== undefined) {
    output.writeFieldBegin('num', Thrift.Type.I32, 2);
    output.writeI32(this.num);
    output.writeFieldEnd();
  }
  if (this.mediaid !== null && this.mediaid !== undefined) {
    output.writeFieldBegin('mediaid', Thrift.Type.I32, 3);
    output.writeI32(this.mediaid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_get_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
OutRecommendService_get_result.prototype = {};
OutRecommendService_get_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.RecommendItem();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_get_result.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_get_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getBySecnario_args = function(args) {
  this.userid = null;
  this.num = null;
  this.mediaid = null;
  this.secnario = null;
  if (args) {
    if (args.userid !== undefined && args.userid !== null) {
      this.userid = args.userid;
    }
    if (args.num !== undefined && args.num !== null) {
      this.num = args.num;
    }
    if (args.mediaid !== undefined && args.mediaid !== null) {
      this.mediaid = args.mediaid;
    }
    if (args.secnario !== undefined && args.secnario !== null) {
      this.secnario = args.secnario;
    }
  }
};
OutRecommendService_getBySecnario_args.prototype = {};
OutRecommendService_getBySecnario_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.userid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.num = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.mediaid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.secnario = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getBySecnario_args.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getBySecnario_args');
  if (this.userid !== null && this.userid !== undefined) {
    output.writeFieldBegin('userid', Thrift.Type.I32, 1);
    output.writeI32(this.userid);
    output.writeFieldEnd();
  }
  if (this.num !== null && this.num !== undefined) {
    output.writeFieldBegin('num', Thrift.Type.I32, 2);
    output.writeI32(this.num);
    output.writeFieldEnd();
  }
  if (this.mediaid !== null && this.mediaid !== undefined) {
    output.writeFieldBegin('mediaid', Thrift.Type.I32, 3);
    output.writeI32(this.mediaid);
    output.writeFieldEnd();
  }
  if (this.secnario !== null && this.secnario !== undefined) {
    output.writeFieldBegin('secnario', Thrift.Type.I32, 4);
    output.writeI32(this.secnario);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getBySecnario_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
OutRecommendService_getBySecnario_result.prototype = {};
OutRecommendService_getBySecnario_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = new ttypes.RecommendItem();
          elem14.read(input);
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getBySecnario_result.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getBySecnario_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        iter15.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getProductId_args = function(args) {
};
OutRecommendService_getProductId_args.prototype = {};
OutRecommendService_getProductId_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getProductId_args.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getProductId_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getProductId_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
OutRecommendService_getProductId_result.prototype = {};
OutRecommendService_getProductId_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getProductId_result.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getProductId_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getAppSecret_args = function(args) {
};
OutRecommendService_getAppSecret_args.prototype = {};
OutRecommendService_getAppSecret_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getAppSecret_args.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getAppSecret_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendService_getAppSecret_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
OutRecommendService_getAppSecret_result.prototype = {};
OutRecommendService_getAppSecret_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OutRecommendService_getAppSecret_result.prototype.write = function(output) {
  output.writeStructBegin('OutRecommendService_getAppSecret_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var OutRecommendServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
OutRecommendServiceClient.prototype = {};
OutRecommendServiceClient.prototype.seqid = function() { return this._seqid; }
OutRecommendServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
OutRecommendServiceClient.prototype.get = function(userid, num, mediaid, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get(userid, num, mediaid);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get(userid, num, mediaid);
  }
};

OutRecommendServiceClient.prototype.send_get = function(userid, num, mediaid) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get', Thrift.MessageType.CALL, this.seqid());
  var args = new OutRecommendService_get_args();
  args.userid = userid;
  args.num = num;
  args.mediaid = mediaid;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

OutRecommendServiceClient.prototype.recv_get = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new OutRecommendService_get_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get failed: unknown result');
};
OutRecommendServiceClient.prototype.getBySecnario = function(userid, num, mediaid, secnario, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBySecnario(userid, num, mediaid, secnario);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBySecnario(userid, num, mediaid, secnario);
  }
};

OutRecommendServiceClient.prototype.send_getBySecnario = function(userid, num, mediaid, secnario) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBySecnario', Thrift.MessageType.CALL, this.seqid());
  var args = new OutRecommendService_getBySecnario_args();
  args.userid = userid;
  args.num = num;
  args.mediaid = mediaid;
  args.secnario = secnario;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

OutRecommendServiceClient.prototype.recv_getBySecnario = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new OutRecommendService_getBySecnario_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBySecnario failed: unknown result');
};
OutRecommendServiceClient.prototype.getProductId = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getProductId();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getProductId();
  }
};

OutRecommendServiceClient.prototype.send_getProductId = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getProductId', Thrift.MessageType.CALL, this.seqid());
  var args = new OutRecommendService_getProductId_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

OutRecommendServiceClient.prototype.recv_getProductId = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new OutRecommendService_getProductId_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getProductId failed: unknown result');
};
OutRecommendServiceClient.prototype.getAppSecret = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getAppSecret();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getAppSecret();
  }
};

OutRecommendServiceClient.prototype.send_getAppSecret = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getAppSecret', Thrift.MessageType.CALL, this.seqid());
  var args = new OutRecommendService_getAppSecret_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

OutRecommendServiceClient.prototype.recv_getAppSecret = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new OutRecommendService_getAppSecret_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getAppSecret failed: unknown result');
};
var OutRecommendServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
OutRecommendServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

OutRecommendServiceProcessor.prototype.process_get = function(seqid, input, output) {
  var args = new OutRecommendService_get_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get.length === 3) {
    Q.fcall(this._handler.get, args.userid, args.num, args.mediaid)
      .then(function(result) {
        var result = new OutRecommendService_get_result({success: result});
        output.writeMessageBegin("get", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get(args.userid, args.num, args.mediaid, function (err, result) {
      if (err == null) {
        var result = new OutRecommendService_get_result((err != null ? err : {success: result}));
        output.writeMessageBegin("get", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

OutRecommendServiceProcessor.prototype.process_getBySecnario = function(seqid, input, output) {
  var args = new OutRecommendService_getBySecnario_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBySecnario.length === 4) {
    Q.fcall(this._handler.getBySecnario, args.userid, args.num, args.mediaid, args.secnario)
      .then(function(result) {
        var result = new OutRecommendService_getBySecnario_result({success: result});
        output.writeMessageBegin("getBySecnario", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getBySecnario", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBySecnario(args.userid, args.num, args.mediaid, args.secnario, function (err, result) {
      if (err == null) {
        var result = new OutRecommendService_getBySecnario_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getBySecnario", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getBySecnario", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

OutRecommendServiceProcessor.prototype.process_getProductId = function(seqid, input, output) {
  var args = new OutRecommendService_getProductId_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getProductId.length === 0) {
    Q.fcall(this._handler.getProductId)
      .then(function(result) {
        var result = new OutRecommendService_getProductId_result({success: result});
        output.writeMessageBegin("getProductId", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getProductId", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getProductId(function (err, result) {
      if (err == null) {
        var result = new OutRecommendService_getProductId_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getProductId", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getProductId", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

OutRecommendServiceProcessor.prototype.process_getAppSecret = function(seqid, input, output) {
  var args = new OutRecommendService_getAppSecret_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getAppSecret.length === 0) {
    Q.fcall(this._handler.getAppSecret)
      .then(function(result) {
        var result = new OutRecommendService_getAppSecret_result({success: result});
        output.writeMessageBegin("getAppSecret", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAppSecret", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getAppSecret(function (err, result) {
      if (err == null) {
        var result = new OutRecommendService_getAppSecret_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getAppSecret", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getAppSecret", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

